name: rds-postgres/security-group
on:
  pull_request:
    branches:
      - main
    paths:
      - rds-postgres/security-group/**
    types:
      - closed
      - opened
      - reopened
      - synchronize
jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    concurrency: ${{ github.workflow }}
    with:
      module: rds-postgres/security-group
    permissions:
      id-token: write
      contents: write
      checks: write
      pull-requests: write
